# Generated by Django 6.1.1 on 2026-10-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Curso')),
                ('instituicao', models.CharField(max_length=150, verbose_name='Instituição')),
                ('categoria', models.CharField(choices=[('FACULDADE', 'Faculdade'), ('ALURA', 'Alura'), ('INGLES', 'Curso de Inglês'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('data_conclusao', models.DateField(verbose_name='Data de Conclusão')),
                ('imagem', models.ImageField(upload_to='certificados/', verbose_name='Imagem do Certificado')),
                ('link_validacao', models.URLField(blank=True, null=True, verbose_name='Link de Validação (Opcional)')),
            ],
            options={
                'ordering': ['-data_conclusao'],
            },
        ),
    ]
